name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          google-chrome --version

      # Install Microsoft Edge
      - name: Install Microsoft Edge
        run: |
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge.list
          sudo apt update
          sudo apt install -y microsoft-edge-stable
          microsoft-edge --version

      # Run TestNG Tests
      - name: Run TestNG Tests
        run: mvn test -Dsurefire.suiteXmlFiles=testng.xml
